### ISSUE TITLE
Memory transport

### ISSUE THREAD

**Issue by inhies** [gomqtt/transport#2]
I have a use-case for an in-memory transport, ie: connecting a client to the broker from the same package that the broker is running in. I would like to do this without incurring the overhead of TCP connections for each client, as there is the possibility of needing a lot of clients. 

Is gomqtt/transport the right package to be discussing this in? Do you think it is a good idea? Would you accept a pull request for it?

**Comment by 256dpi** [comment]
Hi @inhies, if understood you properly, you'd like to use MQTT as an IPC mechanism? If yes I don't know if that is a good idea, as MQTT was designed to be transferred over a wire and might have some overhead compared to just using go's channels. May I'm begin naive but why aren't you not just using channels?

Anyway, the transport package defines similar to net/http `Conn` as an interface. So any struct can implement that interface and act as a connection. However, the higher packages like client and  broker are also using the `Dialer` and `Launcher` interface. But this should be an easy fix. So this would be the right package to implement more connection types.

Maybe you can tell a little more about your use-case?

**Comment by inhies** [comment]
I'm working on a home automation project, and of course I want an MQTT broker for IoT devices to communicate to, so I have a gomqtt/broker running and accepting connections. Internally, I have an as-yet unknown number of other pieces of code that are going to want to utilize MQTT for sending and receiving messages, whether it is sending to a device to change it's state, or receiving information from the device. Examples include an [owntracks](https://github.com/owntracks) service consuming the messages from my phone, or some code that interfaces wiht a [Hue bridge](https://godoc.org/github.com/Collinux/GoHue) and makes my Hue lights controllable over MQTT. 

The way it works right now is internally I have one gomqtt/client that connects to the broker over a tcp socket, that client subscribes to `#`, and then other pieces of code can `subscribe` to it, with whatever topic they want, and they receive a channel that will contain only messages matching that topic. This has been working well until last night when I realized that retained messages will not be sent when a new piece of code subscribes to my main client, because the broker already sent the retained messages. The only way I can see this working is to have my "proxy" client store messages that should retained once it gets them, and then manually pass them out when it gets new subscription requests.

But it seems redundant to store two copies of retained messages when the broker is doing it already. So I was thinking if there was a way to connect to the broker directly through memory it would solve this issue and give the code in the various services more control over their connection, because now they have a genuine gomqtt/client and not just a channel.

**Comment by 256dpi** [comment]
Cool that you're using gomqtt/broker. Up until now I thought I am the only one using it. 😄 

I see two (almost three) possible solutions:

1. It would be totally ok to give each "virtual" client its own gomqtt/client instance as the overhead would be fairly low. AFAIK if you connect using the loopback interface the kernel will anyway do some optimizations I guess... (maybe you're even reading from the others writing buffer).

2. You implement a custom backend for the gomqtt/broker that does the default brokering for MQTT but handles certain messages differently. For example and incoming message for one topic would directly trigger some other code running inside the broker.

3. My intention is anyway to get basics of the broker package in a service package that allows to build servers that use the MQTT protocol but may not actual "broker" messages but process them in a different way.

Which would you prefer?

**Comment by inhies** [comment]
> It would be totally ok to give each "virtual" client its own gomqtt/client instance as the overhead would be fairly low. AFAIK if you connect using the loopback interface the kernel will anyway do some optimizations I guess... (maybe you're even reading from the others writing buffer).

Giving each virtual client it's own gomqtt/client would certainly work, and is the simplest solution, i just worry (perhaps needlessly) about the overhead of doing that. I suppose I could just do it and if it ever becomes an issue then I could pursue one of the other options... 

> You implement a custom backend for the gomqtt/broker that does the default brokering for MQTT but handles certain messages differently. For example and incoming message for one topic would directly trigger some other code running inside the broker.

A custom backend looks to be a lot more complicated than a custom transport.Server, and as of now you can only have one backend per broker but multiple transports. So the backend would need to reproduce the functionality of the existing MemoryBackend as well as the custom callbacks.

> My intention is anyway to get basics of the broker package in a service package that allows to build servers that use the MQTT protocol but may not actual "broker" messages but process them in a different way.

This sounds interesting, and I think would be a great high-level abstraction of MQTT away from the broker package and requiring TCP connections, etc. I would love to see this done either way, but I don't think it would be immediately helpful with my current situation. 

Am I wrong in assuming that implementing a transport.Server that communicates via memory and not sockets would be the easiest way to have a client talking to a broker on the same machine without the overhead of the sockets?

**Comment by 256dpi** [comment]
If you go the custom Server road you also have to implement a custom Conn. As the later is a rather heavy interface I might get a little tedious.

On the other hand the Backend interface is very simple for what it does. And the cool thing is that you can instantiate a MemoryBackend and just call it to do the heavy lifting and only add some code in the Publish method:

```go
type customBackend struct {
  broker.MemoryBackend
}

func (b *customBackend) Publish(client *Client, msg *packet.Message) error {
  err := b.MemoryBackend.Publish(client, msg)
  if err != nil {
    return err
  }

  // do something with msg
}
```
I didn't test the above but I should be really that simple.

**Comment by inhies** [comment]
It looks like this would certainly work to snatch messages as they are published, but I don't think it helps with new virtual clients getting retained messages once they subscribe unless I handle that myself, which I think isn't a great idea. 

I was thinking maybe I could create a new broker.Client for each virtual client, and then subscribe them to topics and send retained messages from the MemoryBackend, but I can't because there is unexported fields in broker.Client.

I've been looking over transport.Conn and while there's a decent amount of methods I should be able to copy most of the packet encoding/decoding things from an existing Conn and then use an io.Pipe for the reader and writer (with the reader going through bufio.NewReader())

**Comment by 256dpi** [comment]
I guess you have to try it out and see what fits best. ;) Please keep me updated about your experiments!

**Comment by 256dpi** [comment]
I'm closing this issue as implementing a memory transport is out of scope of this package.

Rationale: MQTT is not made for inter-process-communication and for testing we already have the `tools` package in place.
